name: Bug Report 🐛
description: File a report to help us improve KT
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP Version
      placeholder: e.g. 8.3
  - type: dropdown
    id: provider
    attributes:
      label: AI Provider
      options:
        - OpenAI
        - DeepSeek
        - Gemini
        - None (Mock Mode)
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we make this bug happen again?
    validations:
      required: true
